### ISSUE TITLE
File Features - Inviting Others

### ISSUE THREAD

**Issue by Zagros5000** [amadrzyk/Code-Editor-Website#1]
Users can input an email address and invite that user to work in a work space or on a file.

Acceptance criteria:

- [ ] The inputted email address exists in the database of registered users.

- [ ] The inputted email address is does not already have access to the file or work space that they were invited to. 

- [ ] The inputted email address must also be able to leave, given they accepted the invitation, thus removing access and the files from their dashboard. A copy of files would be saved upon leaving.

- [ ] Right clicking a file would bring up the invite interface

**Comment by amadrzyk** [comment]
This issue was moved to abhathal/Code-Editor#1
