### ISSUE TITLE
File Features - Modifying

### ISSUE THREAD

**Issue by Zagros5000** [amadrzyk/Code-Editor-Website#2]
Multiple users can view and edit the same file given they have access.

Acceptance criteria:

- [ ] User must have access to file

- [ ] Ownership of the file can be transferred

- [ ] Owner of file can kick and invite users from editing a file or workspace

- [ ] User changes are saved

**Comment by amadrzyk** [comment]
This issue was moved to abhathal/Code-Editor#2
